###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        mem_limit: 512m
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8001:8025'

    mariadb:
        image: 'mariadb:10.4'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=102030
            - MYSQL_DATABASE=econ_economizze
            - MYSQL_USER=localuser
            - MYSQL_PASSWORD=102030
        ports:
            - '8003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '9090:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
